version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable-curl-browsers-legacy
    steps:
      - checkout
      - run:
          name: Pack
          command: zip resourcepack.zip ./*
